name: blumenau
description: "Blumenau tennis club timetable"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  syncfusion_flutter_calendar: ^25.1.35
  syncfusion_localizations: ^25.1.35
  syncfusion_flutter_datagrid: ^25.1.35
  build_runner: ^2.4.8
  hive: ^2.2.3
  path_provider: ^2.1.2
  hive_generator: ^2.0.1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  pinput: ^4.0.0
  mocktail: ^1.0.3
  bloc_test: ^9.1.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png


