name: blumenau
description: "Blumenau tennis club timetable"
version: 1.0.5+1

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  syncfusion_flutter_calendar: ^25.1.35
  syncfusion_localizations: ^25.1.35
  syncfusion_flutter_datagrid: ^25.1.35
  build_runner: ^2.4.8
  hive: ^2.2.3
  path_provider: ^2.1.2
  hive_generator: ^2.0.1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  pinput: ^4.0.0
  mocktail: ^1.0.3
  bloc_test: ^9.1.6
  firebase_core: ^2.27.1  
  firebase_auth: ^4.4.0   
  cloud_firestore: ^4.15.9 
  flutter_launcher_icons: ^0.13.1
  weather: ^3.1.1
  gesture_x_detector: ^1.1.1
  intl: ^0.19.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons: 
  git:
    url: https://github.com/Davenchy/flutter_launcher_icons.git
    ref: fixMinSdkParseFlutter2.8
  image_path: "assets/ic_launcher_foreground.png"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"
  adaptive_icon_background: "assets/ic_launcher_background.png"
  android: true
  ios: true
  remove_alpha_ios: true