name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 build:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v4
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: flutter build windows
     - uses: actions/upload-artifact@master
       with:
          name: windows
          path: build\windows\x64\runner\Release
