name: Flutter

on:
  push:
    branches: [ "mobile" ]
  pull_request:
    branches: [ "mobile" ]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: flutter build apk
     - uses: actions/upload-artifact@master
       with:
          name: android
          path: build/app/outputs/apk/release
